const countries=[
    { "code": "AF", "name": "Afghanistan" },
    { "code": "AL", "name": "Albania" },
    { "code": "DZ", "name": "Algeria" },
    { "code": "AD", "name": "Andorra" },
    { "code": "AO", "name": "Angola" },
    { "code": "AR", "name": "Argentina" },
    { "code": "AM", "name": "Armenia" },
    { "code": "AU", "name": "Australia" },
    { "code": "AT", "name": "Austria" },
    { "code": "AZ", "name": "Azerbaijan" },
    { "code": "BH", "name": "Bahrain" },
    { "code": "BD", "name": "Bangladesh" },
    { "code": "BY", "name": "Belarus" },
    { "code": "BE", "name": "Belgium" },
    { "code": "BZ", "name": "Belize" },
    { "code": "BJ", "name": "Benin" },
    { "code": "BO", "name": "Bolivia" },
    { "code": "BA", "name": "Bosnia and Herzegovina" },
    { "code": "BW", "name": "Botswana" },
    { "code": "BR", "name": "Brazil" },
    { "code": "BG", "name": "Bulgaria" },
    { "code": "CA", "name": "Canada" },
    { "code": "CN", "name": "China" },
    { "code": "CO", "name": "Colombia" },
    { "code": "HR", "name": "Croatia" },
    { "code": "CU", "name": "Cuba" },
    { "code": "CY", "name": "Cyprus" },
    { "code": "CZ", "name": "Czech Republic" },
    { "code": "DK", "name": "Denmark" },
    { "code": "EG", "name": "Egypt" },
    { "code": "FI", "name": "Finland" },
    { "code": "FR", "name": "France" },
    { "code": "DE", "name": "Germany" },
    { "code": "GR", "name": "Greece" },
    { "code": "HK", "name": "Hong Kong" },
    { "code": "IN", "name": "India" },
    { "code": "ID", "name": "Indonesia" },
    { "code": "IR", "name": "Iran" },
    { "code": "IQ", "name": "Iraq" },
    { "code": "IE", "name": "Ireland" },
    { "code": "IT", "name": "Italy" },
    { "code": "JP", "name": "Japan" },
    { "code": "KE", "name": "Kenya" },
    { "code": "KR", "name": "South Korea" },
    { "code": "KW", "name": "Kuwait" },
    { "code": "LB", "name": "Lebanon" },
    { "code": "MY", "name": "Malaysia" },
    { "code": "MX", "name": "Mexico" },
    { "code": "MA", "name": "Morocco" },
    { "code": "NL", "name": "Netherlands" },
    { "code": "NZ", "name": "New Zealand" },
    { "code": "NG", "name": "Nigeria" },
    { "code": "NO", "name": "Norway" },
    { "code": "OM", "name": "Oman" },
    { "code": "PK", "name": "Pakistan" },
    { "code": "PH", "name": "Philippines" },
    { "code": "PL", "name": "Poland" },
    { "code": "PT", "name": "Portugal" },
    { "code": "QA", "name": "Qatar" },
    { "code": "RO", "name": "Romania" },
    { "code": "RU", "name": "Russia" },
    { "code": "SA", "name": "Saudi Arabia" },
    { "code": "SG", "name": "Singapore" },
    { "code": "ZA", "name": "South Africa" },
    { "code": "ES", "name": "Spain" },
    { "code": "SE", "name": "Sweden" },
    { "code": "CH", "name": "Switzerland" },
    { "code": "TH", "name": "Thailand" },
    { "code": "TR", "name": "Turkey" },
    { "code": "UA", "name": "Ukraine" },
    { "code": "AE", "name": "United Arab Emirates" },
    { "code": "GB", "name": "United Kingdom" },
    { "code": "US", "name": "United States" },
    { "code": "VN", "name": "Vietnam" },
    { "code": "YE", "name": "Yemen" },
    { "code": "ZW", "name": "Zimbabwe" }
  ]

  export default countries;